### ISSUE TITLE
Form submit results in an error

### ISSUE THREAD

**Issue by mihhailk** [toomastahves/contact-form#1]
When submitting valid form convertFormToJSON function throws exception: 

> formData.keys is not a function

Seems that not a browser issue, because it happened in Firefox and Chrome both in heroku and local environments.

**Comment by toomastahves** [comment]
Hey, thanks for feedback.

I just tried submitting from Chrome v52 and Firefox v48 through Heroku and it worked:
https://contact-forms.herokuapp.com/#/list

Maybe it's browser compatibility problem with FormData.keys, looks like it was introduced for Chrome v50 and Firfox v44:
https://developer.mozilla.org/en-US/docs/Web/API/FormData#Browser_compatibility

**Comment by mihhailk** [comment]
hei, thanks for your quick response. 

Yeah, it seems that recently updated Chrome with v49 was not enough, updating Firefox helped.

We will send you our complete feedback soon.
